server:
  port: 9080

spring:
  application:
    name: order-api

  jpa:
    hibernate:
    ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        id:
          sequence:
            increment-size-mismatch_strategy: FIX

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  kafka:
    bootstrap-servers: localhost:9092
    enable:
      metrics:
        push: false

    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: order_api_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: com.learning.events # change this with your event packages
      producer:
        acks: -1
        bootstrap-servers: localhost:29092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: Try IntelliJ IDEA Ultimate

logging:
  level:
    kafka: OFF
    br:
      com:
        ambev: INFO

    org:
      hibernate: INFO
      springframework: INFO
      apache:
        kafka:
          clients: OFF


  # Optional: Flyway specific properties (defaults are usually fine)
  flyway:
    enabled: true
  # Specifies the location of migration scripts (default is classpath:db/migration)
    locations: classpath:db/migration

app:
  topic:
    name: order_calcule_topic

management:
  endpoints:
    web:
      exposure:
        include: health,info

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 50

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s
