server:
  port: 9080

spring:
  application:
    name: order-api

#  security:
#    user:
#      name: order-user
#      password: a!m#Com
#      roles: USER,ADMIN

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: localhost:29092
      group-id: order_api_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.learning.events # change this with your event packages
      producer:
        acks: -1
        bootstrap-servers: localhost:29092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
    ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        id:
          sequence:
            increment-size-mismatch_strategy: FIX

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

logging:
  level:
    br:
      com:
        ambev: TRACE

    org:
      hibernate: ERROR
      springframework: TRACE


# Optional: Flyway specific properties (defaults are usually fine)
  flyway:
    enabled: true
  # Specifies the location of migration scripts (default is classpath:db/migration)
    locations: classpath:db/migration

app:
  topic:
    name: order_calcule_topic


